[[headers]]
for = "/*"
  [headers.values]
  X-Content-Type-Options: nosniff

[[edge_functions]]
  path = "/*"
  function = "strip-non-html-headers"

[[plugins]]
package = "netlify-plugin-cache"

  [plugins.inputs]
  paths = [ ".cache" ]