[[headers]]
  for = "/*"
  [headers.values]
    X-Content-Type-Options = "nosniff"
    Cache-Control = "max-age=180, immutable"
    Content-Security-Policy = "default-src 'self'; connect-src https://plausible.io; font-src 'self' https://fonts.googleapis.com https://fonts.gstatic.com https://rsms.me; img-src https://maps.googleapis.com https://media.api-sports.io https://dev.virtualearth.net 'self'; script-src 'sha256-dF0h0b+/zR00U4KnzuyQvwnThwp7s//XCgvBkz4ZUIw='; script-src-elem https://netlify-cdp-loader.netlify.app https://platform.twitter.com https://plausible.io 'self'; frame-src https://app.netlify.com; style-src 'self' 'unsafe-inline' https://fonts.googleapis.com https://rsms.me/;"

[[headers]]
  for = "/*.html"
  [headers.values]
    Cache-Control = "max-age=180, immutable"

[[headers]]
  for = "/*.jpg"
  [headers.values]
    Cache-Control = "max-age=31536000, immutable"

[[headers]]
  for = "/*.ico"
  [headers.values]
    Cache-Control = "max-age=31536000, immutable"

[[headers]]
  for = "/*.css"
  [headers.values]
    Cache-Control = "max-age=31536000, immutable"

[[headers]]
  for = "/*.webmanifest"
  [headers.values]
    Content-Type = "application/manifest+json; charset=utf-8"
    Cache-Control = "max-age=31536000, immutable"

[[headers]]
  for = "/*.vcf"
  [headers.values]
    Content-Type = "text/vcard; charset=utf-8"

[[edge_functions]]
  path = "/*"
  function = "strip-non-html-headers"

[[plugins]]
package = "netlify-plugin-cache"

  [plugins.inputs]
  paths = [
    ".cache",
    "dist/img/clubs",
    "dist/img/common",
    "dist/img/grounds",
    "dist/img/crests"
   ]

[[plugins]]
package = "netlify-plugin-debug-cache"
