[[headers]]
  for = "/*"
  [headers.values]
    X-Content-Type-Options = "nosniff"
    Cache-Control = "max-age=180, immutable"
    Content-Security-Policy = "default-src 'self'; font-src https://fonts.googleapis.com; script-src https://plausible.io; style-src 'unsafe-inline';"

[[headers]]
  for = "/*.html"
  [headers.values]
    Cache-Control = "max-age=180, immutable"

[[headers]]
  for = "/*.jpg"
  [headers.values]
    Cache-Control = "max-age=31536000, immutable"

[[headers]]
  for = "/*.ico"
  [headers.values]
    Cache-Control = "max-age=31536000, immutable"

[[headers]]
  for = "/*.css"
  [headers.values]
    Cache-Control = "max-age=31536000, immutable"

[[headers]]
  for = "/*.webmanifest"
  [headers.values]
    Content-Type = "application/manifest+json; charset=utf-8"
    Cache-Control = "max-age=31536000, immutable"

[[headers]]
  for = "/*.vcf"
  [headers.values]
    Content-Type = "text/vcard; charset=utf-8"

[[edge_functions]]
  path = "/*"
  function = "strip-non-html-headers"

[[plugins]]
package = "netlify-plugin-cache"

  [plugins.inputs]
  paths = [ ".cache" ]