title: "Non-League Grounds"
base: https://www.nonleaguegrounds.com
description: "Non-League football is the lifeblood of the game. It's where the
    game is played, where the fans are, where the stories are."
disclaimer: "Whilst we endeavour to ensure that the information on this website is correct, we do not warrant its completeness or accuracy; nor do we commit to ensuring that the website remains available or that the material on the website is kept up-to-date."
hero:
    home:
        src: /img/samuel-regan-asante-YOtjUyEfClo-unsplash
        author: Samuel Regan-Asante
        id: fkaregan
    clubs:
        src: /img/richard-boyle-KGvLHzpOiaQ-unsplash
        author: Richard Boyle
        id: hellorich
    leagues:
        src: /img/ezequiel-garrido-s6XWkKDKynY-unsplash
        author: Ezequiel Garrido
        id: zegarr
    regions:
        src: /img/william-hook-0er8ezF3Xhg-unsplash
        author: William Hook
        id: williamtm
    grounds:
        src: /img/fancy-crave-qowyMze7jqg-unsplash
        author: Fancy Crave
        id: fancycrave

class:
    table: table is-fullwidth is-striped
