title: "Non-League Grounds"
base: https://www.nonleaguegrounds.com
intro: |
    Kick off your non-league adventure
description: |
    Discover the beauty of grassroots football with a comprehensive directory of non-league English football grounds.
disclaimer: |
    Whilst we endeavour to ensure that the information on this website is 
    correct, we do not warrant its completeness or accuracy; nor do we commit 
    to ensuring that the website remains available or that the material on the
    website is kept up-to-date.
