name: Node.js CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      BING_MAPS_API_KEY: ${{ secrets.BING_MAPS_API_KEY }}

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Cache Eleventy-Img assets
        uses: actions/cache@v3
        with:
          path: |
            ~/.cache
            ~/dist/img/clubs
            ~/dist/img/grounds
          key: |
            eleventy-fetch
            eleventy-img-clubs
            eleventy-img-grounds
      - run: npm ci
      - run: npm run build --if-present
